<?php
/**
 * WCAPF_V4_Migration_Hooks class.
 *
 * @since      4.0.0
 * @package    wc-ajax-product-filter
 * @subpackage wc-ajax-product-filter/includes/migration
 * @author     wptools.io
 */

/**
 * WCAPF_V4_Migration_Hooks class.
 *
 * @since 4.0.0
 */
class WCAPF_V4_Migration_Hooks {

	/**
	 * The constructor.
	 */
	private function __construct() {
	}

	/**
	 * Returns an instance of this class.
	 *
	 * @return WCAPF_V4_Migration_Hooks
	 */
	public static function instance() {
		// Store the instance locally to avoid private static replication
		static $instance = null;

		// Only run these methods if they haven't been run previously
		if ( null === $instance ) {
			$instance = new WCAPF_V4_Migration_Hooks();
			$instance->init_hooks();
		}

		return $instance;
	}

	/**
	 * Hook into actions and filters.
	 */
	private function init_hooks() {
		add_filter( 'wcapf_admin_js_params', array( $this, 'set_v4_migration_js_params' ) );

		// V4 migration notice.
		add_action( 'admin_notices', array( $this, 'show_v4_migration_notice' ) );
		add_action( 'admin_footer', array( $this, 'dismiss_v4_migration_notice_scripts' ) );
		add_action( 'admin_footer', array( $this, 'dismiss_v4_review_filters_notice_scripts' ) );
		add_action( 'wp_ajax_wcapf_dismiss_v4_migration_notice', array( $this, 'dismiss_v4_migration_notice' ) );
		add_action( 'wp_ajax_wcapf_dismiss_v4_review_filters_notice', array(
			$this,
			'dismiss_v4_review_filters_notice'
		) );

		// Notice to upgrade the pro version to v2.
		add_action( 'admin_notices', array( $this, 'show_v2_pro_version_upgrade_notice' ) );
	}

	public function set_v4_migration_js_params( $params ) {
		// v4 migration related data.
		$params['show_v4_migration_notice']      = $this->v4_migration_notice_can_be_shown();
		$params['show_v4_review_filters_notice'] = $this->v4_review_filters_notice_can_be_shown();
		$params['v4_migrated_form_url']          = $this->get_v4_migrated_form_url();
		$params['v4_migration_doc_url']          = $this->get_v4_migration_doc_url();
		$params['show_pro_v2_upgrade_notice']    = $this->pro_v2_upgrade_notice_can_be_shown();

		return $params;
	}

	/**
	 * Determines if the v4 migration notice should be shown.
	 *
	 * @since 4.0.0
	 *
	 * @return bool
	 */
	private function v4_migration_notice_can_be_shown() {
		if ( ! current_user_can( 'manage_options' ) ) {
			return false;
		}

		if ( '1' !== get_option( 'wcapf_v4_migration_notice_status' ) ) {
			return false;
		}

		return true;
	}

	/**
	 * Determines if the v4 migration notice should be shown.
	 *
	 * @since 4.0.0
	 *
	 * @return bool
	 */
	private function v4_review_filters_notice_can_be_shown() {
		if ( ! current_user_can( 'manage_options' ) ) {
			return false;
		}

		if ( '1' !== get_option( 'wcapf_v4_review_filters_notice_status' ) ) {
			return false;
		}

		$screen_id = $this->current_screen_id();

		if ( 'toplevel_page_wcapf' !== $screen_id ) {
			return false;
		}

		$form_id = ! empty( $_GET['id'] ) ? $_GET['id'] : '';

		if ( ! $form_id ) {
			return false;
		}

		if ( get_option( 'wcapf_migrated_filters_form_id' ) != $form_id ) {
			return false;
		}

		return true;
	}

	private function current_screen_id() {
		global $current_screen;

		return isset( $current_screen->id ) ? $current_screen->id : '';
	}

	/**
	 * The form url that is generated by the v4 migration process.
	 *
	 * @since 4.0.0
	 *
	 * @return string
	 */
	public function get_v4_migrated_form_url() {
		$form_id = get_option( 'wcapf_migrated_filters_form_id' );

		if ( $form_id ) {
			$form_edit_url = WCAPF_Helper::form_edit_url( $form_id );
		} else {
			$form_edit_url = WCAPF_Helper::forms_page_url();
		}

		return $form_edit_url;
	}

	/**
	 * @return string
	 */
	public function get_v4_migration_doc_url() {
		return add_query_arg(
			array(
				'utm_source'   => 'WP+Admin',
				'utm_medium'   => 'inside+plugin',
				'utm_campaign' => 'WCAPF+V4+Migration',
			),
			'https://wptools.io/docs/wc-ajax-product-filter/v3-to-v4-migration/'
		);
	}

	/**
	 * Determines if the pro v2 upgrade notice should be shown.
	 *
	 * @since 4.0.0
	 *
	 * @return bool
	 */
	private function pro_v2_upgrade_notice_can_be_shown() {
		if ( ! current_user_can( 'manage_options' ) ) {
			return false;
		}

		if ( ! is_plugin_active( 'wc-ajax-product-filter-pro/wc-ajax-product-filter-pro.php' ) ) {
			return false;
		}

		if ( defined( 'WCAPF_PRO_VERSION' ) && ! version_compare( WCAPF_PRO_VERSION, '2.0.0', '<' ) ) {
			return false;
		}

		return true;
	}

	/**
	 * Show the v4 migration notice.
	 *
	 * @since 4.0.0
	 *
	 * @return void
	 */
	public function show_v4_migration_notice() {
		if ( ! $this->v4_migration_notice_can_be_shown() ) {
			return;
		}

		$form_url          = $this->get_v4_migrated_form_url();
		$migration_doc_url = $this->get_v4_migration_doc_url();
		?>
		<div class="notice notice-info" id="wcapf-v4-migration-notice">
			<p>
				<strong>WCAPF - WooCommerce Ajax Product Filter (v4.0.0 Migration Notice)</strong>
			</p>
			<p>
				The <i>WC Ajax Product Filter</i> plugin has been upgraded to v4.0.0 and is now named <i>WCAPF -
					WooCommerce Ajax Product Filter</i>. We have redesigned the admin UI to provide a more intuitive
				user experience and refactored the codebase for improved performance and easier future enhancements. As
				part of the migration process, a form has been automatically created with all the existing filters from
				your shop. We kindly request that you visit the form and review the order of the filters.
			</p>
			<p>
				<a href="<?php echo esc_url( $form_url ); ?>">Review the filters</a>
				|
				<a href="<?php echo esc_url( $migration_doc_url ); ?>" target="_blank">Learn more about migration</a>
				|
				<a href="javascript:void(0)" onclick="removeWCAPFMigrationNotice()">I understand, remove
					the notice</a>
			</p>
		</div>
		<?php
	}

	/**
	 * The js script to dismiss the v4 migration notice.
	 *
	 * @since 4.0.0
	 *
	 * @return void
	 */
	public function dismiss_v4_migration_notice_scripts() {
		$nonce = wp_create_nonce( 'dismiss-v4-migration-notice-nonce' );
		?>
		<!--suppress ES6ConvertVarToLetConst, JSValidateTypes -->
		<script>
			function removeWCAPFMigrationNotice() {
				var $notice = jQuery( '#wcapf-v4-migration-notice' );

				$notice.fadeOut( 300, function() {
					$notice.remove();
				} );

				var data = {
					action: 'wcapf_dismiss_v4_migration_notice',
					nonce: '<?php echo $nonce; ?>',
				};

				jQuery.post( ajaxurl, data, function( response ) {
					console.log( response );
				} );
			}
		</script>
		<?php
	}

	/**
	 * The js script to dismiss the v4 review filters notice.
	 *
	 * @since 4.0.0
	 *
	 * @return void
	 */
	public function dismiss_v4_review_filters_notice_scripts() {
		if ( ! $this->v4_review_filters_notice_can_be_shown() ) {
			return;
		}

		$nonce = wp_create_nonce( 'dismiss-v4-review-filters-notice-nonce' );
		?>
		<!--suppress ES6ConvertVarToLetConst, JSValidateTypes -->
		<script>
			function removeWCAPFReviewFiltersNotice() {
				var $notice = jQuery( '#wcapf-v4-review-filters-notice' );

				$notice.fadeOut( 300, function() {
					$notice.remove();
				} );

				var data = {
					action: 'wcapf_dismiss_v4_review_filters_notice',
					nonce: '<?php echo $nonce; ?>',
				};

				jQuery.post( ajaxurl, data, function( response ) {
					console.log( response );
				} );
			}
		</script>
		<?php
	}

	/**
	 * Dismiss the v4 migration notice via ajax.
	 *
	 * @since 4.0.0
	 *
	 * @return void
	 */
	public function dismiss_v4_migration_notice() {
		check_ajax_referer( 'dismiss-v4-migration-notice-nonce', 'nonce' );

		update_option( 'wcapf_v4_migration_notice_status', '2' );

		wp_send_json_success( 'v4 migrate notice dismissed' );
	}

	/**
	 * Dismiss the v4 review filters notice via ajax.
	 *
	 * @since 4.0.0
	 *
	 * @return void
	 */
	public function dismiss_v4_review_filters_notice() {
		check_ajax_referer( 'dismiss-v4-review-filters-notice-nonce', 'nonce' );

		update_option( 'wcapf_v4_review_filters_notice_status', '2' );

		wp_send_json_success( 'v4 review filters notice dismissed' );
	}

	/**
	 * Show notice to upgrade the pro version to v2.
	 *
	 * @since 4.0.0
	 *
	 * @return void
	 */
	public function show_v2_pro_version_upgrade_notice() {
		if ( ! $this->pro_v2_upgrade_notice_can_be_shown() ) {
			return;
		}
		?>
		<div class="notice notice-info">
			<p>
				<strong>WCAPF - WooCommerce Ajax Product Filter Pro (Upgrade Required)</strong>
			</p>
			<p>
				Thank you for using the Pro version. To ensure compatibility with <i>WCAPF - WooCommerce Ajax Product
					Filter</i> v4.0.0, it is necessary to upgrade <i>WCAPF - WooCommerce Ajax Product Filter Pro</i> to
				v2.0.0. Please proceed with the upgrade.
			</p>
		</div>
		<?php
	}

}

if ( is_admin() ) {
	WCAPF_V4_Migration_Hooks::instance();
}
